### ISSUE TITLE
[Issue] Twigs Lamps are not rendering itself or the player.

### ISSUE THREAD

**Issue by MaranRoseGIT** [moddingplayground/twigs-fabric#14]
Self-explanatory
![2022-06-17_23 15 56](https://user-images.githubusercontent.com/80443691/174420767-f317b918-04f5-4402-9d0f-173315236bf5.png)

 Holding one of the twigs lamps, it's not rendering me or the player, can confirm I'm "invisible" from other players, this seemed to of happened after the newest fabric loader/api update? Unsure, no error logs; here is my latest.log
 [latest.log](https://github.com/moddingplayground/twigs-fabric/files/8932867/latest.log)
 
 _**Minecraft Fabric 1.18.2**_

**Comment by MaranRoseGIT** [comment]
The issue has been found, It's apparently LambdaDynamicLights https://www.curseforge.com/minecraft/mc-mods/lambdynamiclights

Unsure why it's causing this though, hope to hear from you soon.

**Comment by dvitski** [comment]
https://github.com/moddingplayground/twigs-fabric/blob/34447f53b7681a4acc47b60ade5d78d6a746d8ad/src/main/java/net/moddingplayground/twigs/init/TwigsBlocks.java#L46-L47

I thought this was fixed ages ago, but apparently not!
`createLightLevelFromLitBlockState(int)` uses 17/18, where the maximum value for 'stable' gameplay is 15

This *is* fixed in the 1.19 branch leading version 2.0, which I hope to be released very soon, so I'm hesitant to release a direct fix for this

Also, out of interest, are you using a mod pack or just a jumble of mods that you've put together? Just wondering how easy it would be for you to update to 1.19 in the future :)

**Comment by MaranRoseGIT** [comment]
It's my mod-pack that I have attempted to carefully craft for my players, I am unsure if it is possible to update to 1.19 smoothly, it would most likely be at the end of 2022, by that point most of the mods I have should be updated to 1.19.

Is there any chance at a small patch for 1.18.2 for the time being? If not, I understand.

**Comment by dvitski** [comment]
I'll release a patch soon :)

**Comment by MaranRoseGIT** [comment]
Much appreciated!

**Comment by MaranRoseGIT** [comment]
Oh, I forgot to ask, when will you release this patch, so I can test it out and report back?

**Comment by dvitski** [comment]
I'm not home right now so the best I can say is as soon as possible 😅

**Comment by MaranRoseGIT** [comment]
Alright, thank you!

**Comment by dvitski** [comment]
Due to some real life complications, I'm going to have to push this back a day or two, apologies!

**Comment by MaranRoseGIT** [comment]
> Due to some real life complications, I'm going to have to push this back a day or two, apologies!

Hey, it's alright! I have the entire week to wait, to test this out before I will be busy myself; but as soon as you release it, I'll report back to you asap!

**Comment by dvitski** [comment]
Doing this right now

**Comment by MaranRoseGIT** [comment]
Is it currently in the process of getting uploaded to curseforge?

**Comment by dvitski** [comment]
Yep, just under automatic review at the moment

**Comment by dvitski** [comment]
Approved!

**Comment by MaranRoseGIT** [comment]
It's fixed, thank you so much! Just in time too!
