### ISSUE TITLE
Crashing at starting

### ISSUE THREAD

**Issue by TheButterbrotMan** [moddingplayground/twigs-fabric#2]
https://bytebin.lucko.me/buLN7ZEVSY <- Clientcrashlog

https://bytebin.lucko.me/HdB6caCiHi <- Servercrashlog

**Comment by TheButterbrotMan** [comment]
https://github.com/Bstn1802/AutoReconnect/issues/19

**Comment by TheButterbrotMan** [comment]
https://github.com/Spaceman/FabricSecretRooms/issues/14

**Comment by Bstn1802** [comment]
Quick statement, I have nothing to do with this error in Servercrash log, only with the one in Clientcrashlog but you don't have anything to do with that either, they're completely unrelated.
Small hint, this issue here has something to do with your PaperLanternBlock, which minecraft apparently seems to be confusing with an air block and therefore can't set the direction property on it at which point I'm asking myself if the lanternblock even has a direction property, like why would it need one? Anyways, you have to take it from there, more Info in the crash log, at least I hope you can get more out of it that I could.
